---
- name: Deploy Apache container with volume and read-only access
  hosts: prod
  become: true
  vars_files:
    - secret/cred.yml

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - git
        - wget
        - ca-certificates
        - curl
        - software-properties-common
      when: ansible_facts['os_family'] == 'Debian'
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
        
    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

  tasks:
    - name: Get all containers
      community.docker.docker_host_info:
        containers: true
        containers_filters:
          status:
            - exited
            - running
            - created
            - restarting
            - paused
            - dead
      register: container_info

    - name: Debug Docker Containers
      debug:
        msg: "Container Name: {{ container_info | to_nice_json }}"

    - name: Display container information
      ansible.builtin.debug:
        msg: 
          - "Container: {{ item.Names[0] | replace('/', '') }}"
          - "Status: {{ item.Status }}"
      loop: "{{ container_info.containers }}"
      when: container_info.containers is defined

    - name: Extract Container name
      ansible.builtin.set_fact:
        container_name: "{{ container_info.containers | map(attribute='Names') | flatten | map('replace', '/', '') | list }}"
      tags: extract_container_name

    - name: Debug container_name
      debug:
        var: container_name
        #verbosity: 2


    - name: Stop all containers running with docker before deploying Wordpress
      docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: true
      loop: "{{ container_name }}"
      when: item in container_name
    - name: Remove existing Apache container if it exists
      community.docker.docker_container:
        name: apache
        state: absent
      
        
    - name: Create folder for index.html
      ansible.builtin.file:
        path: /opt/apache-web
        state: directory
        mode: '0755'


    - name: Create copy index.html to the container
      ansible.builtin.template:
        src: index.html.j2
        dest: /opt/apache-web/index.html
        mode: '0644'

    - name: Deploy Apache container with volume mount and read-only access to index.html
      community.docker.docker_container:
        name: apache
        image: httpd:latest
        state: started
        mounts:
          - type: bind
            source: /opt/apache-web/index.html
            target: /usr/local/apache2/htdocs/index.html
            read_only: true
        ports:
          - "80:80"